function [stats_tracos, stats_ideal, stats_bcs, colcoding, colcoding_bcs] = f_stats_MooringSetup(mod_option,wbr_option,ebr_option,vst_option,eof_option,sur_option,idr_option,test_suffix)

% function to compute statistics for INALT/VIKING Mooring AMOCg transport,
% based on files generated by f_cut_MooringSetup

% input:
% mod_option: choose model INALT20 (1) or VIKING20X (2)
% wbr_option: choose WB4 setup as ideal (0), initial (1), current (2), or enhanced (3)
% ebr_option: choose EB1 setup as
%       ideal (0), initial (1), current (2), or enhanced (3), or ideal averaged to climatological year (4) 
% vst_option: choose vertical structure as determined by
%       stepwise integration (1, Johns 2005), T'/S' interpolation (2, Williams 2015), EOF regression (3), or (0) if wbr and ebr ideal
% eof_option: choose number EOFs as whether the first 1 (1) or 2 (2) or 3 (3) EOFs are used, choose (0) if vst~=3
% sur_option: choose SSS like
%       normal measurement (0), climatological year (1), anomaly equals uppermost instrument - Williams 2015 (2),
%       seasonal extrapolation - McCarthy 2015 (3), climatological value - McCarthy 2015 (4)
% idr_option: choose integration approach
%       from surface (1) or from level of nomo (2), EB1 from EBb4 (BP1200) - highpass filtered (3),
%       EB1 from EBb4, WB4 from WBb6 - highpass filtered (4), same as 3 but not filtered (5)
% test_suffix: adds a suffix in the saved file name in code testing cases, string, default ''

% output:
% stats_tracos : statistics for the performance of the tested AMOCg reconstruction
% stats_ideal: statistics of the model-truth for comparison
% colcoding: colour coding level used to categorize performance

if mod_option == 1
    nmid = 'INA';
elseif mod_option == 2
    nmid = 'VIK';
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% --- loading and preparing ---
file_name = ['wbr' num2str(wbr_option) 'ebr' num2str(ebr_option) '_vst' num2str(vst_option) 'eof' num2str(eof_option) 'sur' num2str(sur_option) '_idr' num2str(idr_option)  '_' nmid test_suffix];
tracos = load(['/Users/ahans/Documents/PhD/DATA/Model/' nmid '20/interim_' nmid '_v4/moor_' file_name '.mat']);
time_mly = tracos.time_mly;
tracos.AMOCg_interior_mly = tracos.AMOCg;

% loading ideal transport for comparison
ideal = load(['/Users/ahans/Documents/PhD/DATA/Model/' nmid '20/interim_' nmid '_v4/vg_1100S_' nmid '.mat']);
% calculate their monthly means
[yy,mm,~] = datevec(ideal.time);
for i = 1:length(time_mly)
    ideal.psig_mly(:,i) = mean(ideal.psig(:,datenum(yy,mm,15)==time_mly(i)),2);
    ideal.Tg_wbeb_mly(:,i) = mean(ideal.Tg_wb(:,datenum(yy,mm,15)==time_mly(i)) + ideal.Tg_shelf_eb(:,datenum(yy,mm,15)==time_mly(i)),2);
end
[ideal.AMOCg_mly,~] = max(ideal.psig_mly.*1e-6,[],1,'omitnan');

% adding boundary transport to array estimate
ideal.AMOCg_wbeb_mly = sum(ideal.Tg_wbeb_mly(ideal.dep_grid<=max(tracos.dep_grid),:).*10,1).*1e-6;
tracos.AMOCg_mly = tracos.AMOCg_interior_mly + ideal.AMOCg_wbeb_mly;

% compare anomalies
ideal_AMOCg_mly_mean = mean(ideal.AMOCg_mly);
ideal.AMOCg_mly = ideal.AMOCg_mly - ideal_AMOCg_mly_mean;
tracos_AMOCg_mly_mean = mean(tracos.AMOCg_mly);
tracos.AMOCg_mly = tracos.AMOCg_mly - tracos_AMOCg_mly_mean;

% --- statistics for resulting transport ---
[stats_tracos, stats_ideal, colcoding] = f_stats_calc(time_mly,tracos.AMOCg_mly,ideal.AMOCg_mly);

% add mean to stats and colcoding
stats_tracos.mean = tracos_AMOCg_mly_mean;
stats_ideal.mean = ideal_AMOCg_mly_mean;

error_mean = abs(stats_ideal.mean - stats_tracos.mean) / stats_ideal.mean;
limits_relative = [0.4 0.1];
if error_mean >= limits_relative(1)
    colcoding.mean = 0;
elseif error_mean >= limits_relative(2)
    colcoding.mean = 1;
else
    colcoding.mean = 2;
end

% add stats for boundary currents only
ideal_AMOCg_wbeb_mly_mean = mean(ideal.AMOCg_wbeb_mly);
ideal.AMOCg_wbeb_mly = ideal.AMOCg_wbeb_mly - ideal_AMOCg_wbeb_mly_mean;
[stats_bcs, ~, colcoding_bcs] = f_stats_calc(time_mly,ideal.AMOCg_wbeb_mly,ideal.AMOCg_mly);

stats_bcs.mean = ideal_AMOCg_wbeb_mly_mean;
error_mean = abs(stats_ideal.mean - stats_bcs.mean) / stats_ideal.mean;
if error_mean >= limits_relative(1)
    colcoding_bcs.mean = 0;
elseif error_mean >= limits_relative(2)
    colcoding_bcs.mean = 1;
else
    colcoding_bcs.mean = 2;
end
