function [stats_tracos, stats_ideal, colcoding] = f_stats_BPRSetup(mod_option,posbpr_option,possla_option,prc_option,ebr_option,ref_option,vst_option,stp_option,test_suffix)

% function to compute statistics for INALT/VIKING BPR AMOCg transport,
% based on files generated by f_cut_BPRSetup

% input:
% mod_option: choose model INALT20 (1) or VIKING20X (2)
% posbpr_option: choose which postition to use for BPR at WB (1 or 2)
% possla_option: choose SLA at BPR 300m/1200m position (1) or at the boundary (2)
% prc_option: choose processing of BPRs as
%       original timeseries (0), every 2.3yrs detrended (1), 2 yrs highpass filtered (2),
%       original values + WB low drift (AZA version) corresponding to Sonardyne maximum (31), RBR maximum (32), RBR median (33), fictive (34),
%       every 2.3yrs detrended + WB IES annual data (4),
%       EB 2.3yrs detrended and WB with velocity field and WB4 current setup density (5),
%       EB 2.3yrs detrended and WB with velocity field and WB4 enhanced setup density (6),
%       or like 2 and also SSH highpass filtered (7)
% ebb_option: choose EB gap filling as
%       using original data (0), annual + semiannual harmonics (1), reconstruction from 1200m with density (2),
%       same as 2 with with density contribution high pass filtered (3)
% ref_option: choose reference level at 1100m (1), 900m (2), or 1300m (3)
% vst_option: choose vertical structure as
%       EOF regression with no motion (1), EOF regression with known motion (2),
%       linear interpolation (3), spline interpolation (4),
%       EOF regression and linear interpolation combined - possible for stp2 or stp6 (5)
% stp_option: choose setup as reconstruction of
%       300m and 500m (1), only 500m (2), only 300m (3), 300m, 500m and 1200m (4), 500m and 1200m (5), only 1200m (6)
% test_suffix: adds a suffix in the saved file name in code testing cases, string, default ''

% output:
% stats_tracos : statistics for the performance of the tested AMOCg reconstruction
% stats_ideal: statistics of the model-truth for comparison
% colcoding: colour coding level used to categorize performance

if mod_option == 1
    nmid = 'INA';
elseif mod_option == 2
    nmid = 'VIK';
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% --- loading and preparing ---
file_name = ['pos' num2str(posbpr_option) num2str(possla_option) '_prc' num2str(prc_option) '_ebb' num2str(ebr_option) '_ref' num2str(ref_option) '_vst' num2str(vst_option) '_stp' num2str(stp_option) '_' nmid test_suffix];
tracos = load(['/Users/ahans/Documents/PhD/DATA/Model/' nmid '20/interim_' nmid '_v4/bpr_' file_name '.mat']);
time_mly = tracos.time_mly;

% loading ideal transport for comparison
ideal = load(['/Users/ahans/Documents/PhD/DATA/Model/' nmid '20/interim_' nmid '_v4/vg_1100S_' nmid '.mat']);
% calculate their monthly means
[yy,mm,~] = datevec(ideal.time);
for i = 1:length(time_mly)
    ideal.psig_mly(:,i) = mean(ideal.psig(:,datenum(yy,mm,15)==time_mly(i)),2);
end
[ideal.AMOCg_mly,~] = max(ideal.psig_mly.*1e-6,[],1,'omitnan');
ideal.AMOCg_mly = ideal.AMOCg_mly - mean(ideal.AMOCg_mly); % anomalies to fit time series from BPR

% --- statistics for resulting transport ---
[stats_tracos, stats_ideal, colcoding] = f_stats_calc(time_mly,tracos.AMOCg,ideal.AMOCg_mly);


% --- statistics if bottom pressure is reconstructed ---
if ebr_option == 2 || ebr_option == 3 || prc_option == 4 || prc_option == 5 || prc_option == 6
    if ebr_option == 2 || ebr_option == 3 
        bp.bpa_300_orig = tracos.bpa_eb300_mly_orig;
        bp.bpa_300_test = tracos.bpa_eb300_mly;
        bp.bpa_500_orig = tracos.bpa_eb500_mly_orig;
        bp.bpa_500_test = tracos.bpa_eb500_mly;
    elseif prc_option == 5 || prc_option == 6
        bp.bpa_300_orig = tracos.bpa_wb300_mly_orig;
        bp.bpa_300_test = tracos.bpa_wb300_mly;
        bp.bpa_500_orig = tracos.bpa_wb500_mly_orig;
        bp.bpa_500_test = tracos.bpa_wb500_mly;
    elseif prc_option == 4
        bp.bpa_300_test = tracos.bpa_wb300_mly;
        bp.bpa_500_test = tracos.bpa_wb500_mly;
        orig = load(['/Users/ahans/Documents/PhD/DATA/Model/' nmid '20/interim_' nmid '_v4/bpr_pos22_prc5_ebb0_ref1_vst1_stp1_' nmid '.mat']);
        bp.bpa_300_orig = orig.bpa_wb300_mly_orig;
        bp.bpa_500_orig = orig.bpa_wb500_mly_orig;
    end

    % detrending
    bp.bpa_300_orig_dtr = detrend(bp.bpa_300_orig,'linear');
    bp.bpa_500_orig_dtr = detrend(bp.bpa_500_orig,'linear');
    bp.bpa_300_test_dtr = detrend(bp.bpa_300_test,'linear');
    bp.bpa_500_test_dtr = detrend(bp.bpa_500_test,'linear');
    % filtering
    Fs = 1/(30*24*3600); % Sampling frequency in Hz (monthly)
    Fc_lp = 1/(5*365*24*3600); % Cutoff frequency in Hz
    [b, a] = butter(2, Fc_lp/(Fs/2), 'low'); % 2nd-order low-pass filter
    bp.bpa_300_orig_lp = filtfilt(b, a, bp.bpa_300_orig_dtr);
    bp.bpa_500_orig_lp = filtfilt(b, a, bp.bpa_500_orig_dtr);
    bp.bpa_300_test_lp = filtfilt(b, a, bp.bpa_300_test_dtr);
    bp.bpa_500_test_lp = filtfilt(b, a, bp.bpa_500_test_dtr);
    Fc_hp = 1/(2*365*24*3600); % Cutoff frequency in Hz
    [b, a] = butter(1, Fc_hp/(Fs/2), 'high'); % 1st-order high-pass filter
    bp.bpa_300_orig_hp = filtfilt(b, a, bp.bpa_300_orig_dtr);
    bp.bpa_500_orig_hp = filtfilt(b, a, bp.bpa_500_orig_dtr);
    bp.bpa_300_test_hp = filtfilt(b, a, bp.bpa_300_test_dtr);
    bp.bpa_500_test_hp = filtfilt(b, a, bp.bpa_500_test_dtr);
    % cutting half the filter length in the beginning and end
    bp.bpa_300_orig_lp = bp.bpa_300_orig_lp(31:end-30);
    bp.bpa_500_orig_lp = bp.bpa_500_orig_lp(31:end-30);
    bp.bpa_300_test_lp = bp.bpa_300_test_lp(31:end-30);
    bp.bpa_500_test_lp = bp.bpa_500_test_lp(31:end-30);
    bp.bpa_300_orig_hp = bp.bpa_300_orig_hp(13:end-12);
    bp.bpa_500_orig_hp = bp.bpa_500_orig_hp(13:end-12);
    bp.bpa_300_test_hp = bp.bpa_300_test_hp(13:end-12);
    bp.bpa_500_test_hp = bp.bpa_500_test_hp(13:end-12);
    
    % rmse
    rmse_300 = rmse(bp.bpa_300_orig,bp.bpa_300_test);
    rmse_500 = rmse(bp.bpa_500_orig,bp.bpa_500_test);
    rmse_300_hp = rmse(bp.bpa_300_orig_hp,bp.bpa_300_test_hp);
    rmse_500_hp = rmse(bp.bpa_500_orig_hp,bp.bpa_500_test_hp);
    rmse_300_lp = rmse(bp.bpa_300_orig_lp,bp.bpa_300_test_lp);
    rmse_500_lp = rmse(bp.bpa_500_orig_lp,bp.bpa_500_test_lp);
    disp(['rmse 300: ' num2str(rmse_300,'%.4f') ' ' num2str(rmse_300_hp,'%.4f') ' ' num2str(rmse_300_lp,'%.4f')])
    disp(['rmse 500: ' num2str(rmse_500,'%.4f') ' ' num2str(rmse_500_hp,'%.4f') ' ' num2str(rmse_500_lp,'%.4f')])
    
    % corr
    corr_300 = corr(bp.bpa_300_orig',bp.bpa_300_test');
    corr_500 = corr(bp.bpa_500_orig',bp.bpa_500_test');
    corr_300_hp = corr(bp.bpa_300_orig_hp',bp.bpa_300_test_hp');
    corr_500_hp = corr(bp.bpa_500_orig_hp',bp.bpa_500_test_hp');
    corr_300_lp = corr(bp.bpa_300_orig_lp',bp.bpa_300_test_lp');
    corr_500_lp = corr(bp.bpa_500_orig_lp',bp.bpa_500_test_lp');
    disp(['corr 300: ' num2str(corr_300,'%.2f') ' ' num2str(corr_300_hp,'%.2f') ' ' num2str(corr_300_lp,'%.2f')])
    disp(['corr 500: ' num2str(corr_500,'%.2f') ' ' num2str(corr_500_hp,'%.2f') ' ' num2str(corr_500_lp,'%.2f')])
    
    % trend
    disp('Slopes per year:')
    mdl_orig_300 = fitlm(time_mly(time_mly>=datenum(1994,1,1)), bp.bpa_300_orig(time_mly>=datenum(1994,1,1)));
    disp(['orig 300: ' num2str(mdl_orig_300.Coefficients.Estimate(2) * 365.25,'%.5f')])
    mdl_test_300 = fitlm(time_mly(time_mly>=datenum(1994,1,1)), bp.bpa_300_test(time_mly>=datenum(1994,1,1)));
    disp(['test 300: ' num2str(mdl_test_300.Coefficients.Estimate(2) * 365.25,'%.5f')])
    mdl_orig_500 = fitlm(time_mly(time_mly>=datenum(1994,1,1)), bp.bpa_500_orig(time_mly>=datenum(1994,1,1)));
    disp(['orig 500: ' num2str(mdl_orig_500.Coefficients.Estimate(2) * 365.25,'%.5f')])
    mdl_test_500 = fitlm(time_mly(time_mly>=datenum(1994,1,1)), bp.bpa_500_test(time_mly>=datenum(1994,1,1)));
    disp(['test 500: ' num2str(mdl_test_500.Coefficients.Estimate(2) * 365.25,'%.5f')])

    diff300 = bp.bpa_300_orig - bp.bpa_300_test;
    diff500 = bp.bpa_500_orig - bp.bpa_500_test;

    % figure
    figure()
    tiledlayout(3,1,'TileSpacing','compact','Padding','compact')
    nexttile
    plot(tracos.time_mly,bp.bpa_300_orig,'k','Linewidth',2); hold on; plot(tracos.time_mly,bp.bpa_300_test,'m','LineWidth',2); datetick
    legend('300m BP ideal','300m BP reconstr','NumColumns',2)
    nexttile
    plot(tracos.time_mly,bp.bpa_500_orig,'k','Linewidth',2); hold on; plot(tracos.time_mly,bp.bpa_500_test,'b','LineWidth',2); datetick
    legend('500m BP ideal','500m BP reconstr','NumColumns',2)
    nexttile
    plot(diff300,'m','Linewidth',2); hold on
    plot(diff500,'b','Linewidth',2); datetick
    legend('Error 300m BP reconstr','Error 500m BP reconstr','NumColumns',2)
    set(gcf,'Position',[400 200 622 510])

    figure() % hp
    tiledlayout(3,1,'TileSpacing','compact','Padding','compact')
    nexttile
    plot(tracos.time_mly(13:end-12),bp.bpa_300_orig_hp,'k','Linewidth',2); hold on; plot(tracos.time_mly(13:end-12),bp.bpa_300_test_hp,'m','LineWidth',2); datetick
    legend('300m BP ideal hp','300m BP reconstr hp','NumColumns',2)
    nexttile
    plot(tracos.time_mly(13:end-12),bp.bpa_500_orig_hp,'k','Linewidth',2); hold on; plot(tracos.time_mly(13:end-12),bp.bpa_500_test_hp,'b','LineWidth',2); datetick
    legend('500m BP ideal hp','500m BP reconstr hp','NumColumns',2)
    nexttile
    plot(bp.bpa_300_orig_hp - bp.bpa_300_test_hp,'m','Linewidth',2); hold on
    plot(bp.bpa_500_orig_hp - bp.bpa_500_test_hp,'b','Linewidth',2); datetick
    legend('Error 300m BP reconstr hp','Error 500m BP reconstr hp','NumColumns',2)
    set(gcf,'Position',[400 200 622 510])

    figure() % lp
    tiledlayout(3,1,'TileSpacing','compact','Padding','compact')
    nexttile
    plot(tracos.time_mly(31:end-30),bp.bpa_300_orig_lp,'k','Linewidth',2); hold on; plot(tracos.time_mly(31:end-30),bp.bpa_300_test_lp,'m','LineWidth',2); datetick
    legend('300m BP ideal lp','300m BP reconstr','NumColumns',2)
    nexttile
    plot(tracos.time_mly(31:end-30),bp.bpa_500_orig_lp,'k','Linewidth',2); hold on; plot(tracos.time_mly(31:end-30),bp.bpa_500_test_lp,'b','LineWidth',2); datetick
    legend('500m BP ideal lp','500m BP reconstr','NumColumns',2)
    nexttile
    plot(bp.bpa_300_orig_lp - bp.bpa_300_test_lp,'m','Linewidth',2); hold on
    plot(bp.bpa_500_orig_lp - bp.bpa_500_test_lp,'b','Linewidth',2); datetick
    legend('Error 300m BP reconstr lp','Error 500m BP reconstr','NumColumns',2)
    set(gcf,'Position',[400 200 622 510])

    % error distribution
    figure();
    tiledlayout(2,2,'TileSpacing','compact','Padding','compact')
    nexttile
    histogram(diff300)
    title('BP 300m')
    set(gca,'FontSize',15)
    nexttile
    histogram(diff500)
    title('BP 500m')
    set(gca,'FontSize',15)
    nexttile
    qqplot(diff300)
    set(gca,'FontSize',15)
    nexttile
    qqplot(diff500)
    set(gca,'FontSize',15)
    
    [lillie_h, lillie_p] = lillietest(diff300); % h=0 confirms null hypothesis -> confirms normal distribution
    [jb_h, jb_p] = jbtest(diff300);
    [ad_h, ad_p] = adtest(diff300);
    fprintf('300: Lilliefors test: h=%d, p=%.4f\n', lillie_h, lillie_p);
    fprintf('300: Jarque-Bera test: h=%d, p=%.4f\n', jb_h, jb_p);
    fprintf('300: Anderson-Darling test: h=%d, p=%.4f\n', ad_h, ad_p);

    [lillie_h, lillie_p] = lillietest(diff500);
    [jb_h, jb_p] = jbtest(diff500);
    [ad_h, ad_p] = adtest(diff500);
    fprintf('500: Lilliefors test: h=%d, p=%.4f\n', lillie_h, lillie_p);
    fprintf('500: Jarque-Bera test: h=%d, p=%.4f\n', jb_h, jb_p);
    fprintf('500: Anderson-Darling test: h=%d, p=%.4f\n', ad_h, ad_p);

end
